-- ADICIONANDO COLUNAS
ALTER TABLE T_TESTE_DL ADD DS_EMAIL VARCHAR(80);
ALTER TABLE T_TESTE_DDL ADD (DS_OBS1 VARCHAR2(50) NOT NULL, DS_OBS2 VARCHAR2(50));

-- MODIFICAÇÕES
ALTER TABLE T_TESTE_DDL MODIFY DS_OBS1 VARCHAR2(80);
ALTER TABLE T_TESTE_DDL MODIFY NM_TESTE CHAR(30);
ALTER TABLE T_TESTE_DDL MODIFY DS_OBS1 NULL;
ALTER TABLE T_TESTE_DDL MODIFY DS_TESTE NOT NULL;
ALTER TABLE T_TESTE_DDL MODIFY NM_TESTE VARCHAR2(40) NULL;
ALTER TABLE T_TESTE_DDL MODIFY DT_TESTE DEFAULT SYSDATE;

-- REMOVENDO COLUNAS
ALTER TABLE T_TESTE_DDL DROP COLUMN DS_OBS2;
ALTER TABLE T_TESTE_DDL DROP (DS_TESTE, DS_OBS1);

-- REMOVENDO CONSTRAINTS
ALTER TABLE T_TESTE_DDL DROP CONSTRAINT PK_TESTE_DDL;
ALTER TABLE T_TESTE_DDL DROP CONSTRAINT FK_NOME_CONSTRAINT_FOREIGN_KEY;
ALTER TABLE T_TESTE_DDL DROP CONSTRAINT UN_TESTE_DDL_NOME;
ALTER TABLE T_TESTE_DDL DROP CONSTRAINT CK_NOME_CONSTRAINT_CHECK;

-- REMOVER DEFAULT
ALTER TABLE T_TESTE_DDL MODIFY DT_TESTE DEFAULT NULL;

-- RENOMEANDO
ALTER TABLE T_TESTE_DDL RENAME TO T_TESTE_DDL_NOVO;
ALTER TABLE T_TESTE_DDL_NOVO RENAME COLUMN DS_EMAIL TO DS_EMAIL_NOVO;
ALTER TABLE T_TESTE_DDL_NOVO RENAME CONSTRAINT UN_TESTE_DDL_NOME TO UN_TESTE_DDL_NOME_NOVO;

-- HABILITANDO / DESABILITANDO CONSTRAINTS
ALTER TABLE T_TESTE_DDL_NOVO DISABLE CONSTRAINT UN_TESTE_DDL_NOME_NOVO;
ALTER TABLE T_TESTE_DDL_NOVO ENABLE CONSTRAINT UN_TESTE_DDL_NOME_NOVO;
