-- CRIAÇÃO DA TABELA T_TESTE_DDL
CREATE TABLE T_TESTE_DDL(
    CD_TESTE    NUMBER(3) NOT NULL,
    NM_TESTE    VARCHAR2(30) NOT NULL,
    DS_TESTE    VARCHAR2(60),
    DT_TESTE    DATE
);

-- CONSTRAINTS
ALTER TABLE T_TESTE_DDL ADD CONSTRAINT PK_TESTE_DDL PRIMARY KEY (CD_TESTE);
ALTER TABLE T_TESTE_DDL ADD CONSTRAINT UN_TESTE_DDL_NOME UNIQUE (NM_TESTE);
ALTER TABLE T_TESTE_DDL ADD CONSTRAINT UN_TESTE_DDL_DESC UNIQUE (DS_TESTE);

-- TABELA T_SIP_DEPARTAMENTO
CREATE TABLE T_SIP_DEPARTAMENTO (
    CD_DEPTO NUMBER(3) NOT NULL,
    NM_DEPTO VARCHAR(30) NOT NULL,
    SD_DEPTO CHAR(3) NOT NULL
);

-- CONSTRAINTS T_SIP_DEPARTAMENTO
ALTER TABLE T_SIP_DEPARTAMENTO ADD CONSTRAINT PK_SIP_DEPARTAMENTO PRIMARY KEY (CD_DEPTO);
ALTER TABLE T_SIP_DEPARTAMENTO ADD CONSTRAINT UN_SIP_DEPTO_NOME UNIQUE (NM_DEPTO);
ALTER TABLE T_SIP_DEPARTAMENTO ADD CONSTRAINT UN_SIP_DEPTO_SIGLA UNIQUE (SD_DEPTO);
