-- INSERINDO DADOS EM T_SIP_DEPARTAMENTO
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (1, 'Departamento A', 'D01');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (2, 'Departamento B', 'D02');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (3, 'Departamento C', 'D03');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (4, 'Departamento D', 'D04');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (5, 'Departamento E', 'D05');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (6, 'Departamento F', 'D06');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (7, 'Departamento G', 'D07');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (8, 'Departamento H', 'D08');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (9, 'Departamento I', 'D09');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (10, 'Departamento J', 'D10');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (11, 'Departamento K', 'D11');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (12, 'Departamento L', 'D12');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (13, 'Departamento M', 'D13');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (14, 'Departamento N', 'D14');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (15, 'Departamento O', 'D15');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (16, 'Departamento P', 'D16');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (17, 'Departamento Q', 'D17');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (18, 'Departamento R', 'D18');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (19, 'Departamento S', 'D19');
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SD_DEPTO) VALUES (20, 'Departamento T', 'D20');

COMMIT;
